### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Killerzombie468** [segabl/pd2-mind-blown#1]
Application has crashed: C++ exception
mods/pd2-mind-blown-master/mod.lua:64: attempt to compare nil with number

SCRIPT STACK

value() @mods/pd2-mind-blown-master/mod.lua:58
_notify() lib/utils/messagesystem.lua:60
update() lib/utils/messagesystem.lua:74
original() lib/managers/playermanager.lua:591
update() @mods/base/req/core/Hooks.lua:265
original() lib/setups/setup.lua:882
update() @mods/base/req/core/Hooks.lua:188
update() lib/setups/gamesetup.lua:745
update() lib/setups/networkgamesetup.lua:21
original() core/lib/setups/coresetup.lua:557
@mods/base/req/core/Hooks.lua:265

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.109.35
	CPU : Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1650 / nvldumd.dll[30.0.14.7196]
	Language : english
	Memory :     8135MB 504KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Headphones (Corsair HS60 Surround Adapter))

Not sure what it is that's causing is it low memory?

**Comment by segabl** [comment]
Do you use any skill rebalance mods?

**Comment by Killerzombie468** [comment]
I use a skill balancer to nerf some skills but thats about it? I'll see if it helps thank you!

**Comment by segabl** [comment]
this is something that would happen if the skill rebalance loads after mind blown, so if you want to use both, try to add a higher priority to the skill rebalance in the mod.txt
